// Marionette.NET — Source Generator emitter
//
// Renders a ManifestModel to a single-file Marionette.g.cs in the
// `Marionette.Generated` namespace. The emitted code is the runtime's manifest
// contract — see the descriptor records at the bottom of this file.
//
// AOT contract (PHASE0_FINDINGS implications #6, #13):
//   * No `MakeGenericMethod` / `MakeGenericType`
//   * No `Activator.CreateInstance(Type, ...)`
//   * No `Type.GetType(string)`
//   * No `MethodInfo.Invoke`
//   * Every dispatcher is a typed lambda baked at compile time
//
// The emitter NEVER reads ISymbol/Compilation here — it only renders the
// equatable model values. This is what makes the generator cache correctly:
// identical models produce identical output without re-running the validator.

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Marionette.SourceGenerator.Model;

namespace Marionette.SourceGenerator;

internal static class Emitter
{
    /// <summary>
    /// Header banner emitted at the top of every generated file. Includes the
    /// `auto-generated` marker so analyzers / formatting tools skip the file.
    /// </summary>
    public const string Header =
        "// <auto-generated by Marionette.NET source generator />" + "\n" +
        "// Do not edit this file by hand. Changes will be overwritten on the next build.\n" +
        "//\n" +
        "// This file is the compile-time manifest of MCP entrypoints declared in the\n" +
        "// containing assembly. The Marionette runtime consumes the static\n" +
        "// `Marionette.Generated.GeneratedManifest.Roots` collection to register MCP\n" +
        "// tools and resources without runtime reflection over user assemblies.\n";

    public static string EmitManifest(ManifestModel model)
    {
        var sb = new StringBuilder(capacity: 4096);
        sb.Append(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Marionette.Generated;");
        sb.AppendLine();

        EmitGeneratedManifestClass(sb, model);
        sb.AppendLine();
        EmitDescriptorTypes(sb);

        return sb.ToString();
    }

    /// <summary>
    /// Always-emit a placeholder when no roots are present. The runtime's
    /// `IManifestProvider` discovery looks for the well-known type name and
    /// would otherwise fall back to a brittle "no manifest found" path.
    /// </summary>
    public static string EmitEmptyManifest(string assemblyName) =>
        EmitManifest(new ManifestModel(
            AssemblyName: assemblyName,
            Roots: EquatableArray<RootModel>.Empty,
            Diagnostics: EquatableArray<DiagnosticInfo>.Empty));

    // -------------------------------------------------------------------------
    // GeneratedManifest static class
    // -------------------------------------------------------------------------

    private static void EmitGeneratedManifestClass(StringBuilder sb, ManifestModel model)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time manifest of MCP entrypoints emitted by the Marionette.NET");
        sb.AppendLine("/// source generator. The runtime enumerates <see cref=\"Roots\"/> at startup;");
        sb.AppendLine("/// every dispatcher is a typed delegate so this surface is AOT-clean.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedManifest");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The user assembly this manifest was generated for.</summary>");
        sb.Append("    public const string AssemblyName = \"");
        sb.Append(EscapeString(model.AssemblyName));
        sb.AppendLine("\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// All [McpRoot]-decorated classes discovered in the assembly, in the");
        sb.AppendLine("    /// order they were emitted by the generator.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<RootDescriptor> Roots { get; } = new RootDescriptor[]");
        sb.AppendLine("    {");

        foreach (var root in model.Roots.AsEnumerable())
        {
            EmitRootDescriptor(sb, root);
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
    }

    private static void EmitRootDescriptor(StringBuilder sb, RootModel root)
    {
        // We use PascalCase named arguments because C# records expose their
        // primary-ctor parameters as both PascalCase properties AND the same
        // ctor parameter names (case-sensitive). Named-arg syntax must match
        // the parameter casing in the record's positional ctor.
        sb.AppendLine("        new RootDescriptor(");
        sb.Append("            Name: \""); sb.Append(EscapeString(root.ManifestName)); sb.AppendLine("\",");
        sb.Append("            TypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(root.TypeFullName))); sb.AppendLine("\",");

        // Factory: `() => new T()` if a public parameterless ctor exists,
        // otherwise `null`. The runtime can still bind to an existing instance
        // through later phases.
        if (root.HasParameterlessCtor)
        {
            sb.Append("            Create: static () => new ");
            sb.Append(root.TypeFullName);
            sb.AppendLine("(),");
        }
        else
        {
            sb.AppendLine("            Create: null,");
        }

        EmitCallables(sb, root);
        EmitObservables(sb, root);
        EmitTriggerables(sb, root);

        sb.AppendLine("        ),");
    }

    // -------------------------------------------------------------------------
    // Callables — the AOT-critical Invoke lambdas
    // -------------------------------------------------------------------------

    private static void EmitCallables(StringBuilder sb, RootModel root)
    {
        if (root.Callables.Length == 0)
        {
            sb.AppendLine("            Callables: global::System.Array.Empty<CallableDescriptor>(),");
            return;
        }

        sb.AppendLine("            Callables: new CallableDescriptor[]");
        sb.AppendLine("            {");
        foreach (var callable in root.Callables.AsEnumerable())
        {
            EmitCallableDescriptor(sb, root, callable);
        }
        sb.AppendLine("            },");
    }

    private static void EmitCallableDescriptor(StringBuilder sb, RootModel root, CallableModel call)
    {
        sb.AppendLine("                new CallableDescriptor(");
        sb.Append("                    Name: \""); sb.Append(EscapeString(call.MethodName)); sb.AppendLine("\",");
        sb.Append("                    Description: \""); sb.Append(EscapeString(call.Description)); sb.AppendLine("\",");
        sb.Append("                    OffUiThread: "); sb.Append(call.OffUiThread ? "true" : "false"); sb.AppendLine(",");
        sb.Append("                    TimeoutSeconds: "); sb.Append(call.TimeoutSeconds.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
        sb.Append("                    IsAsync: "); sb.Append(call.ReturnsTask ? "true" : "false"); sb.AppendLine(",");

        // Parameters block
        if (call.Parameters.Length == 0)
        {
            sb.AppendLine("                    Parameters: global::System.Array.Empty<ParamDescriptor>(),");
        }
        else
        {
            sb.AppendLine("                    Parameters: new ParamDescriptor[]");
            sb.AppendLine("                    {");
            foreach (var p in call.Parameters.AsEnumerable())
            {
                sb.Append("                        new ParamDescriptor(Name: \"");
                sb.Append(EscapeString(p.Name));
                sb.Append("\", ClrTypeName: \"");
                sb.Append(EscapeString(StripGlobalPrefix(p.TypeFullName)));
                sb.Append("\", IsRequired: ");
                sb.Append(p.IsRequired ? "true" : "false");
                sb.Append(", DefaultValue: ");
                sb.Append(EmitDefaultValueAsObject(p));
                sb.AppendLine("),");
            }
            sb.AppendLine("                    },");
        }

        // Invoke lambda. This is the AOT-critical bit:
        //   static (instance, args) => {
        //       var typed = (Foo)instance;
        //       var a = (int)args["a"]!;
        //       var b = args.TryGetValue("b", out var bRaw) ? (int)bRaw! : 5;  // default
        //       var result = typed.Add(a, b);
        //       return result;
        //   }
        sb.AppendLine("                    Invoke: static (instance, args) =>");
        sb.AppendLine("                    {");
        sb.Append("                        var typed = (");
        sb.Append(root.TypeFullName);
        sb.AppendLine(")instance;");

        foreach (var p in call.Parameters.AsEnumerable())
        {
            EmitParameterUnboxing(sb, p);
        }

        // Build the call expression.
        var argsList = string.Join(", ",
            call.Parameters.AsEnumerable().Select(p => SafeIdentifier(p.Name)));

        if (call.ReturnsTaskOfT)
        {
            // Task<T> / ValueTask<T> — return the task as object?, runtime awaits + unboxes.
            sb.Append("                        return typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(");");
        }
        else if (call.ReturnsTask)
        {
            // Task / ValueTask — return as object?, runtime awaits.
            sb.Append("                        return typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(");");
        }
        else if (call.ReturnTypeFullName == "global::System.Void" || call.ReturnTypeFullName == "void")
        {
            // void — call and return null.
            sb.Append("                        typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(");");
            sb.AppendLine("                        return null;");
        }
        else
        {
            // Sync, non-void — return the value (boxed automatically for value types).
            sb.Append("                        return typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(");");
        }

        sb.AppendLine("                    }),");
    }

    private static void EmitParameterUnboxing(StringBuilder sb, ParameterModel p)
    {
        var ident = SafeIdentifier(p.Name);
        var type = p.TypeFullName;

        if (p.IsRequired)
        {
            // Required: must be present.
            sb.Append("                        var ");
            sb.Append(ident);
            sb.Append(" = (");
            sb.Append(type);
            sb.Append(")args[\"");
            sb.Append(EscapeString(p.Name));
            sb.AppendLine("\"]!;");
        }
        else
        {
            // Optional: try to read; fall back to default literal.
            sb.Append("                        var ");
            sb.Append(ident);
            sb.Append(" = args.TryGetValue(\"");
            sb.Append(EscapeString(p.Name));
            sb.Append("\", out var __raw_");
            sb.Append(ident);
            sb.Append(") ? (");
            sb.Append(type);
            sb.Append(")__raw_");
            sb.Append(ident);
            sb.Append("! : (");
            sb.Append(type);
            sb.Append(")(");
            sb.Append(p.DefaultLiteral ?? "default(" + type + ")");
            sb.AppendLine(");");
        }
    }

    /// <summary>
    /// Render a literal as `object?`. Bools/numbers/null come straight through;
    /// strings are quoted with `(object?)"..."` to keep type inference happy.
    /// </summary>
    private static string EmitDefaultValueAsObject(ParameterModel p)
    {
        if (p.DefaultLiteral is null) return "null";
        return "(object?)(" + p.DefaultLiteral + ")";
    }

    // -------------------------------------------------------------------------
    // Observables
    // -------------------------------------------------------------------------

    private static void EmitObservables(StringBuilder sb, RootModel root)
    {
        if (root.Observables.Length == 0)
        {
            sb.AppendLine("            Observables: global::System.Array.Empty<ObservableDescriptor>(),");
            return;
        }

        sb.AppendLine("            Observables: new ObservableDescriptor[]");
        sb.AppendLine("            {");
        foreach (var obs in root.Observables.AsEnumerable())
        {
            sb.AppendLine("                new ObservableDescriptor(");
            sb.Append("                    Name: \""); sb.Append(EscapeString(obs.PropertyName)); sb.AppendLine("\",");
            sb.Append("                    Description: \""); sb.Append(EscapeString(obs.Description)); sb.AppendLine("\",");
            sb.Append("                    Watchable: "); sb.Append(obs.Watchable ? "true" : "false"); sb.AppendLine(",");
            sb.Append("                    PollingIntervalMs: "); sb.Append(obs.PollingIntervalMs.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
            sb.Append("                    ClrTypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(obs.PropertyTypeFullName))); sb.AppendLine("\",");
            sb.Append("                    Read: static (instance) => ((");
            sb.Append(root.TypeFullName);
            sb.Append(")instance).");
            sb.Append(obs.PropertyName);
            sb.AppendLine("),");
        }
        sb.AppendLine("            },");
    }

    // -------------------------------------------------------------------------
    // Triggerables
    // -------------------------------------------------------------------------

    private static void EmitTriggerables(StringBuilder sb, RootModel root)
    {
        if (root.Triggerables.Length == 0)
        {
            sb.AppendLine("            Triggerables: global::System.Array.Empty<TriggerableDescriptor>()");
            return;
        }

        sb.AppendLine("            Triggerables: new TriggerableDescriptor[]");
        sb.AppendLine("            {");
        foreach (var trig in root.Triggerables.AsEnumerable())
        {
            sb.AppendLine("                new TriggerableDescriptor(");
            sb.Append("                    Name: \""); sb.Append(EscapeString(trig.PropertyName)); sb.AppendLine("\",");
            sb.Append("                    Description: \""); sb.Append(EscapeString(trig.Description)); sb.AppendLine("\",");
            sb.Append("                    Strategy: (global::Marionette.TriggerStrategy)"); sb.Append(trig.Strategy.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
            sb.Append("                    ControlTypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(trig.ControlTypeFullName))); sb.AppendLine("\",");
            sb.Append("                    ResolveControl: static (instance) => ((");
            sb.Append(root.TypeFullName);
            sb.Append(")instance).");
            sb.Append(trig.PropertyName);
            sb.AppendLine("),");
        }
        sb.AppendLine("            }");
    }

    // -------------------------------------------------------------------------
    // Descriptor record types — emitted inline so each user assembly is
    // self-contained. The runtime's IManifestProvider discovery binds via the
    // well-known `Marionette.Generated.GeneratedManifest` type name.
    // -------------------------------------------------------------------------

    private static void EmitDescriptorTypes(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Describes a single [McpRoot]-decorated class.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed record RootDescriptor(");
        sb.AppendLine("    string Name,");
        sb.AppendLine("    string TypeName,");
        sb.AppendLine("    global::System.Func<object>? Create,");
        sb.AppendLine("    global::System.Collections.Generic.IReadOnlyList<CallableDescriptor> Callables,");
        sb.AppendLine("    global::System.Collections.Generic.IReadOnlyList<ObservableDescriptor> Observables,");
        sb.AppendLine("    global::System.Collections.Generic.IReadOnlyList<TriggerableDescriptor> Triggerables);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Describes a single [McpCallable] method. <see cref=\"Invoke\"/> is a");
        sb.AppendLine("/// strongly-typed dispatcher emitted by the source generator (no reflection).");
        sb.AppendLine("/// For void methods it returns null; for Task / Task&lt;T&gt; methods it returns the");
        sb.AppendLine("/// task instance and the runtime awaits it.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed record CallableDescriptor(");
        sb.AppendLine("    string Name,");
        sb.AppendLine("    string Description,");
        sb.AppendLine("    bool OffUiThread,");
        sb.AppendLine("    int TimeoutSeconds,");
        sb.AppendLine("    bool IsAsync,");
        sb.AppendLine("    global::System.Collections.Generic.IReadOnlyList<ParamDescriptor> Parameters,");
        sb.AppendLine("    global::System.Func<object, global::System.Collections.Generic.IReadOnlyDictionary<string, object?>, object?> Invoke);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>One parameter on a CallableDescriptor.</summary>");
        sb.AppendLine("public sealed record ParamDescriptor(");
        sb.AppendLine("    string Name,");
        sb.AppendLine("    string ClrTypeName,");
        sb.AppendLine("    bool IsRequired,");
        sb.AppendLine("    object? DefaultValue);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Describes a single [McpObservable] property.</summary>");
        sb.AppendLine("public sealed record ObservableDescriptor(");
        sb.AppendLine("    string Name,");
        sb.AppendLine("    string Description,");
        sb.AppendLine("    bool Watchable,");
        sb.AppendLine("    int PollingIntervalMs,");
        sb.AppendLine("    string ClrTypeName,");
        sb.AppendLine("    global::System.Func<object, object?> Read);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Describes a single [McpTriggerable] property.</summary>");
        sb.AppendLine("public sealed record TriggerableDescriptor(");
        sb.AppendLine("    string Name,");
        sb.AppendLine("    string Description,");
        sb.AppendLine("    global::Marionette.TriggerStrategy Strategy,");
        sb.AppendLine("    string ControlTypeName,");
        sb.AppendLine("    global::System.Func<object, object?> ResolveControl);");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static string EscapeString(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        foreach (var c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    private static string StripGlobalPrefix(string s) =>
        s.StartsWith("global::", System.StringComparison.Ordinal) ? s.Substring("global::".Length) : s;

    /// <summary>
    /// Reserved-keyword guard. If a parameter happens to be named like a C#
    /// keyword (e.g. <c>class</c>, <c>new</c>) we prefix with <c>@</c>.
    /// </summary>
    private static string SafeIdentifier(string name)
    {
        if (s_csharpKeywords.Contains(name)) return "@" + name;
        return name;
    }

    private static readonly HashSet<string> s_csharpKeywords = new(System.StringComparer.Ordinal)
    {
        "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
        "continue","decimal","default","delegate","do","double","else","enum","event","explicit",
        "extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int",
        "interface","internal","is","lock","long","namespace","new","null","object","operator","out",
        "override","params","private","protected","public","readonly","ref","return","sbyte","sealed",
        "short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
        "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"
    };
}
