// Marionette.NET — Source Generator emitter
//
// Renders a ManifestModel to a single-file Marionette.g.cs in the
// `Marionette.Generated` namespace. The emitted code is the runtime's manifest
// contract — see the descriptor records at the bottom of this file.
//
// AOT contract (PHASE0_FINDINGS implications #6, #13):
//   * No `MakeGenericMethod` / `MakeGenericType`
//   * No `Activator.CreateInstance(Type, ...)`
//   * No `Type.GetType(string)`
//   * No `MethodInfo.Invoke`
//   * Every dispatcher is a typed lambda baked at compile time
//
// The emitter NEVER reads ISymbol/Compilation here — it only renders the
// equatable model values. This is what makes the generator cache correctly:
// identical models produce identical output without re-running the validator.

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Marionette.SourceGenerator.Model;

namespace Marionette.SourceGenerator;

internal static class Emitter
{
    /// <summary>
    /// Header banner emitted at the top of every generated file. Includes the
    /// `auto-generated` marker so analyzers / formatting tools skip the file.
    /// </summary>
    public const string Header =
        "// <auto-generated by Marionette.NET source generator />" + "\n" +
        "// Do not edit this file by hand. Changes will be overwritten on the next build.\n" +
        "//\n" +
        "// This file is the compile-time manifest of MCP entrypoints declared in the\n" +
        "// containing assembly. The Marionette runtime consumes the static\n" +
        "// `Marionette.Generated.GeneratedManifest.Roots` collection to register MCP\n" +
        "// tools and resources without runtime reflection over user assemblies.\n";

    public static string EmitManifest(ManifestModel model)
    {
        var sb = new StringBuilder(capacity: 4096);
        sb.Append(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // Phase 1.2 ownership change: descriptor record types live in
        // Marionette.NET.Runtime under `Marionette.Runtime.Manifest`. The
        // generator references them via `using` instead of emitting per-assembly
        // copies. See src/Marionette.NET.Runtime/Manifest/Descriptors.cs for the
        // full rationale.
        sb.AppendLine("using Marionette.Runtime.Manifest;");
        sb.AppendLine();
        sb.AppendLine("namespace Marionette.Generated;");
        sb.AppendLine();

        EmitGeneratedManifestClass(sb, model);

        // Phase 8.1: emit a hand-written JsonSerializerContext for [McpEvent]
        // args types. Skipped when no event has a source-gen-eligible args
        // type — the runtime then falls back to its legacy reflection-based
        // serialisation path (which carries the [RequiresUnreferencedCode]
        // annotation honoured at the MarionetteHost.RunAsync boundary).
        var jsonTypes = model.EventArgsJsonTypes.AsEnumerable()
            .ToList();
        if (jsonTypes.Count > 0)
        {
            JsonContextEmitter.Emit(sb, jsonTypes);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Always-emit a placeholder when no roots are present. The runtime's
    /// `IManifestProvider` discovery looks for the well-known type name and
    /// would otherwise fall back to a brittle "no manifest found" path.
    /// </summary>
    public static string EmitEmptyManifest(string assemblyName) =>
        EmitManifest(new ManifestModel(
            AssemblyName: assemblyName,
            Roots: EquatableArray<RootModel>.Empty,
            Diagnostics: EquatableArray<DiagnosticInfo>.Empty));

    // -------------------------------------------------------------------------
    // GeneratedManifest static class
    // -------------------------------------------------------------------------

    private static void EmitGeneratedManifestClass(StringBuilder sb, ManifestModel model)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time manifest of MCP entrypoints emitted by the Marionette.NET");
        sb.AppendLine("/// source generator. The runtime enumerates <see cref=\"Roots\"/> at startup;");
        sb.AppendLine("/// every dispatcher is a typed delegate so this surface is AOT-clean.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedManifest");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The user assembly this manifest was generated for.</summary>");
        sb.Append("    public const string AssemblyName = \"");
        sb.Append(EscapeString(model.AssemblyName));
        sb.AppendLine("\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// All [McpRoot]-decorated classes discovered in the assembly, in the");
        sb.AppendLine("    /// order they were emitted by the generator.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<RootDescriptor> Roots { get; } = new RootDescriptor[]");
        sb.AppendLine("    {");

        foreach (var root in model.Roots.AsEnumerable())
        {
            EmitRootDescriptor(sb, root);
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
    }

    private static void EmitRootDescriptor(StringBuilder sb, RootModel root)
    {
        // We use PascalCase named arguments because C# records expose their
        // primary-ctor parameters as both PascalCase properties AND the same
        // ctor parameter names (case-sensitive). Named-arg syntax must match
        // the parameter casing in the record's positional ctor.
        sb.AppendLine("        new RootDescriptor(");
        sb.Append("            Name: \""); sb.Append(EscapeString(root.ManifestName)); sb.AppendLine("\",");
        sb.Append("            TypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(root.TypeFullName))); sb.AppendLine("\",");

        // Factory: `() => new T()` if a public parameterless ctor exists,
        // otherwise `null`. The runtime can still bind to an existing instance
        // through later phases.
        if (root.HasParameterlessCtor)
        {
            sb.Append("            Create: static () => new ");
            sb.Append(root.TypeFullName);
            sb.AppendLine("(),");
        }
        else
        {
            sb.AppendLine("            Create: null,");
        }

        EmitCallables(sb, root);
        EmitObservables(sb, root);
        EmitTriggerables(sb, root);
        EmitEvents(sb, root);

        sb.AppendLine("        ),");
    }

    // -------------------------------------------------------------------------
    // Callables — the AOT-critical Invoke lambdas
    // -------------------------------------------------------------------------

    private static void EmitCallables(StringBuilder sb, RootModel root)
    {
        if (root.Callables.Length == 0)
        {
            sb.AppendLine("            Callables: global::System.Array.Empty<CallableDescriptor>(),");
            return;
        }

        sb.AppendLine("            Callables: new CallableDescriptor[]");
        sb.AppendLine("            {");
        foreach (var callable in root.Callables.AsEnumerable())
        {
            EmitCallableDescriptor(sb, root, callable);
        }
        sb.AppendLine("            },");
    }

    private static void EmitCallableDescriptor(StringBuilder sb, RootModel root, CallableModel call)
    {
        sb.AppendLine("                new CallableDescriptor(");
        sb.Append("                    Name: \""); sb.Append(EscapeString(call.MethodName)); sb.AppendLine("\",");
        sb.Append("                    Description: \""); sb.Append(EscapeString(call.Description)); sb.AppendLine("\",");
        sb.Append("                    OffUiThread: "); sb.Append(call.OffUiThread ? "true" : "false"); sb.AppendLine(",");
        sb.Append("                    TimeoutSeconds: "); sb.Append(call.TimeoutSeconds.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
        sb.Append("                    IsAsync: "); sb.Append(call.ReturnsTask ? "true" : "false"); sb.AppendLine(",");

        // Parameters block
        if (call.Parameters.Length == 0)
        {
            sb.AppendLine("                    Parameters: global::System.Array.Empty<ParamDescriptor>(),");
        }
        else
        {
            sb.AppendLine("                    Parameters: new ParamDescriptor[]");
            sb.AppendLine("                    {");
            foreach (var p in call.Parameters.AsEnumerable())
            {
                sb.Append("                        new ParamDescriptor(Name: \"");
                sb.Append(EscapeString(p.Name));
                sb.Append("\", ClrTypeName: \"");
                sb.Append(EscapeString(StripGlobalPrefix(p.TypeFullName)));
                sb.Append("\", IsRequired: ");
                sb.Append(p.IsRequired ? "true" : "false");
                sb.Append(", DefaultValue: ");
                sb.Append(EmitDefaultValueAsObject(p));
                sb.AppendLine("),");
            }
            sb.AppendLine("                    },");
        }

        // Phase 2.2: pre-computed parameter object schema. Stamped onto the
        // dynamic per-method MCP tool's InputSchema at runtime. Single-line
        // JSON, deterministic, derived at compile-time so the runtime never
        // walks ITypeSymbol.
        sb.Append("                    ParametersJsonSchema: \"");
        sb.Append(EscapeString(call.ParametersJsonSchema));
        sb.AppendLine("\",");

        // Invoke lambda. This is the AOT-critical bit:
        //   static (instance, args) => {
        //       var typed = (Foo)instance;
        //       var a = (int)args["a"]!;
        //       var b = args.TryGetValue("b", out var bRaw) ? (int)bRaw! : 5;  // default
        //       var result = typed.Add(a, b);
        //       return result;
        //   }
        sb.AppendLine("                    Invoke: static (instance, args) =>");
        sb.AppendLine("                    {");
        sb.Append("                        var typed = (");
        sb.Append(root.TypeFullName);
        sb.AppendLine(")instance;");

        foreach (var p in call.Parameters.AsEnumerable())
        {
            EmitParameterUnboxing(sb, p);
        }

        // Build the call expression.
        var argsList = string.Join(", ",
            call.Parameters.AsEnumerable().Select(p => SafeIdentifier(p.Name)));

        if (call.ReturnsTaskOfT)
        {
            // Task<T> / ValueTask<T>: wrap in a typed async lambda that boxes
            // the awaited result into Task<object?>. The runtime can then
            // await Task<object?> directly without MakeGenericMethod /
            // reflective Task<T>.Result reads (Phase 4.2 AOT-hardening).
            //
            // Shape:
            //   static async global::System.Threading.Tasks.Task<object?> __wrap()
            //   {
            //       var __r = await typed.Foo(args).ConfigureAwait(false);
            //       return (object?)__r;
            //   }
            //   return __wrap();
            //
            // We inline the helper as a local function so each callable owns
            // its own closure (closures capture `typed` + parameter locals
            // by reference, which the C# compiler handles correctly).
            sb.AppendLine("                        async global::System.Threading.Tasks.Task<object?> __wrapAsync()");
            sb.AppendLine("                        {");
            // Whether the source returns Task<T> or ValueTask<T>, awaiting
            // works the same — `await` patterns are duck-typed by the C#
            // compiler. The `(object?)` cast boxes value-type results.
            sb.Append("                            var __r = await typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(").ConfigureAwait(false);");
            sb.AppendLine("                            return (object?)__r;");
            sb.AppendLine("                        }");
            sb.AppendLine("                        return __wrapAsync();");
        }
        else if (call.ReturnsTask)
        {
            // Task / ValueTask (no T): wrap into Task<object?> returning null
            // on completion. Same rationale as the Task<T> branch — keeps the
            // runtime's await path reflection-free (Phase 4.2 AOT-hardening).
            sb.AppendLine("                        async global::System.Threading.Tasks.Task<object?> __wrapAsync()");
            sb.AppendLine("                        {");
            sb.Append("                            await typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(").ConfigureAwait(false);");
            sb.AppendLine("                            return null;");
            sb.AppendLine("                        }");
            sb.AppendLine("                        return __wrapAsync();");
        }
        else if (call.ReturnTypeFullName == "global::System.Void" || call.ReturnTypeFullName == "void")
        {
            // void — call and return null.
            sb.Append("                        typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(");");
            sb.AppendLine("                        return null;");
        }
        else
        {
            // Sync, non-void — return the value (boxed automatically for value types).
            sb.Append("                        return typed.");
            sb.Append(call.MethodName);
            sb.Append("(");
            sb.Append(argsList);
            sb.AppendLine(");");
        }

        sb.AppendLine("                    }),");
    }

    private static void EmitParameterUnboxing(StringBuilder sb, ParameterModel p)
    {
        var ident = SafeIdentifier(p.Name);
        var tempSuffix = TempIdentifierSuffix(ident);
        var type = p.TypeFullName;
        var rawIdent = "__raw_" + tempSuffix;
        var jsonIdent = "__json_" + tempSuffix;

        if (p.IsRequired)
        {
            // Required: must be present. Runtime-marshalled primitives arrive
            // already typed; complex values arrive as JsonElement and are
            // deserialized here where the exact generic CLR type is known.
            sb.Append("                        var ");
            sb.Append(rawIdent);
            sb.Append(" = args[\"");
            sb.Append(EscapeString(p.Name));
            sb.AppendLine("\"];");
            sb.Append("                        ");
            sb.Append(type);
            sb.Append(' ');
            sb.Append(ident);
            sb.Append(" = ");
            EmitJsonAwareConversion(sb, type, rawIdent, jsonIdent, p.EnumTypeFullName);
            sb.AppendLine(";");
        }
        else
        {
            // Optional: try to read; fall back to default literal.
            sb.Append("                        ");
            sb.Append(type);
            sb.Append(' ');
            sb.Append(ident);
            sb.AppendLine(";");
            sb.Append("                        if (args.TryGetValue(\"");
            sb.Append(EscapeString(p.Name));
            sb.Append("\", out var ");
            sb.Append(rawIdent);
            sb.AppendLine("))");
            sb.AppendLine("                        {");
            sb.Append("                            ");
            sb.Append(ident);
            sb.Append(" = ");
            EmitJsonAwareConversion(sb, type, rawIdent, jsonIdent, p.EnumTypeFullName);
            sb.AppendLine(";");
            sb.AppendLine("                        }");
            sb.AppendLine("                        else");
            sb.AppendLine("                        {");
            sb.Append("                            ");
            sb.Append(ident);
            sb.Append(" = (");
            sb.Append(type);
            sb.Append(")(");
            sb.Append(p.DefaultLiteral ?? "default(" + type + ")");
            sb.AppendLine(");");
            sb.AppendLine("                        }");
        }
    }

    private static void EmitJsonAwareConversion(
        StringBuilder sb,
        string type,
        string rawIdent,
        string jsonIdent,
        string? enumTypeFullName)
    {
        sb.Append(rawIdent);
        sb.Append(" is global::System.Text.Json.JsonElement ");
        sb.Append(jsonIdent);
        if (enumTypeFullName is not null)
        {
            sb.Append(" ? (");
            sb.Append(type);
            sb.Append(")global::System.Enum.Parse(typeof(");
            sb.Append(enumTypeFullName);
            sb.Append("), ");
            sb.Append(jsonIdent);
            sb.Append(".ValueKind == global::System.Text.Json.JsonValueKind.String ? ");
            sb.Append(jsonIdent);
            sb.Append(".GetString()! : ");
            sb.Append(jsonIdent);
            sb.Append(".GetRawText()) : (");
        }
        else
        {
            sb.Append(" ? global::System.Text.Json.JsonSerializer.Deserialize<");
            sb.Append(type);
            sb.Append(">(");
            sb.Append(jsonIdent);
            sb.Append(".GetRawText())! : (");
        }
        sb.Append(type);
        sb.Append(")");
        sb.Append(rawIdent);
        sb.Append('!');
    }

    /// <summary>
    /// Render a literal as `object?`. Bools/numbers/null come straight through;
    /// strings are quoted with `(object?)"..."` to keep type inference happy.
    /// </summary>
    private static string EmitDefaultValueAsObject(ParameterModel p)
    {
        if (p.DefaultLiteral is null) return "null";
        return "(object?)(" + p.DefaultLiteral + ")";
    }

    // -------------------------------------------------------------------------
    // Observables
    // -------------------------------------------------------------------------

    private static void EmitObservables(StringBuilder sb, RootModel root)
    {
        if (root.Observables.Length == 0)
        {
            sb.AppendLine("            Observables: global::System.Array.Empty<ObservableDescriptor>(),");
            return;
        }

        sb.AppendLine("            Observables: new ObservableDescriptor[]");
        sb.AppendLine("            {");
        foreach (var obs in root.Observables.AsEnumerable())
        {
            sb.AppendLine("                new ObservableDescriptor(");
            sb.Append("                    Name: \""); sb.Append(EscapeString(obs.PropertyName)); sb.AppendLine("\",");
            sb.Append("                    Description: \""); sb.Append(EscapeString(obs.Description)); sb.AppendLine("\",");
            sb.Append("                    Watchable: "); sb.Append(obs.Watchable ? "true" : "false"); sb.AppendLine(",");
            sb.Append("                    PollingIntervalMs: "); sb.Append(obs.PollingIntervalMs.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
            sb.Append("                    ClrTypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(obs.PropertyTypeFullName))); sb.AppendLine("\",");
            sb.Append("                    Read: static (instance) => ((");
            sb.Append(root.TypeFullName);
            sb.Append(")instance).");
            sb.Append(obs.PropertyName);
            sb.AppendLine("),");
        }
        sb.AppendLine("            },");
    }

    // -------------------------------------------------------------------------
    // Triggerables
    // -------------------------------------------------------------------------

    private static void EmitTriggerables(StringBuilder sb, RootModel root)
    {
        if (root.Triggerables.Length == 0)
        {
            sb.AppendLine("            Triggerables: global::System.Array.Empty<TriggerableDescriptor>(),");
            return;
        }

        sb.AppendLine("            Triggerables: new TriggerableDescriptor[]");
        sb.AppendLine("            {");
        foreach (var trig in root.Triggerables.AsEnumerable())
        {
            sb.AppendLine("                new TriggerableDescriptor(");
            sb.Append("                    Name: \""); sb.Append(EscapeString(trig.PropertyName)); sb.AppendLine("\",");
            sb.Append("                    Description: \""); sb.Append(EscapeString(trig.Description)); sb.AppendLine("\",");
            sb.Append("                    Strategy: (global::Marionette.TriggerStrategy)"); sb.Append(trig.Strategy.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
            sb.Append("                    ControlTypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(trig.ControlTypeFullName))); sb.AppendLine("\",");
            sb.Append("                    ResolveControl: static (instance) => ((");
            sb.Append(root.TypeFullName);
            sb.Append(")instance).");
            sb.Append(trig.PropertyName);
            sb.AppendLine("),");
        }
        sb.AppendLine("            },");
    }

    // -------------------------------------------------------------------------
    // Events (Phase 1.6)
    // -------------------------------------------------------------------------

    private static void EmitEvents(StringBuilder sb, RootModel root)
    {
        if (root.Events.Length == 0)
        {
            sb.AppendLine("            Events: global::System.Array.Empty<EventDescriptor>()");
            return;
        }

        sb.AppendLine("            Events: new EventDescriptor[]");
        sb.AppendLine("            {");
        foreach (var ev in root.Events.AsEnumerable())
        {
            EmitEventDescriptor(sb, root, ev);
        }
        sb.AppendLine("            }");
    }

    private static void EmitEventDescriptor(StringBuilder sb, RootModel root, EventModel ev)
    {
        sb.AppendLine("                new EventDescriptor(");
        sb.Append("                    Name: \""); sb.Append(EscapeString(ev.EventName)); sb.AppendLine("\",");
        sb.Append("                    Description: \""); sb.Append(EscapeString(ev.Description)); sb.AppendLine("\",");
        sb.Append("                    ArgsTypeName: \""); sb.Append(EscapeString(StripGlobalPrefix(ev.ArgsTypeFullName))); sb.AppendLine("\",");
        sb.Append("                    ArgsJsonSchema: \""); sb.Append(EscapeString(ev.ArgsJsonSchema)); sb.AppendLine("\",");
        sb.Append("                    MinIntervalMs: "); sb.Append(ev.MinIntervalMs.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
        sb.Append("                    MaxQueueSize: "); sb.Append(ev.MaxQueueSize.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");
        sb.Append("                    CoalesceWindowMs: "); sb.Append(ev.CoalesceWindowMs.ToString(CultureInfo.InvariantCulture)); sb.AppendLine(",");

        // Subscribe lambda — strongly typed at compile time. Two shapes:
        //   * EventHandler<TArgs>: hooks `(s, e) => callback(e)` and detaches
        //     on dispose.
        //   * EventHandler (no T): hooks `(s, e) => callback(e)` against the
        //     non-generic EventHandler signature; e is EventArgs.
        sb.AppendLine("                    Subscribe: static (instance, callback) =>");
        sb.AppendLine("                    {");
        sb.Append("                        var typed = ("); sb.Append(root.TypeFullName); sb.AppendLine(")instance;");

        if (ev.HasArgsType)
        {
            sb.Append("                        global::System.EventHandler<");
            sb.Append(ev.ArgsTypeFullName);
            sb.AppendLine("> handler = (s, e) => callback(e);");
            sb.Append("                        typed.");
            sb.Append(ev.EventName);
            sb.AppendLine(" += handler;");
            sb.Append("                        return new global::Marionette.NET.Runtime.Internal.HandlerDisposable(() => typed.");
            sb.Append(ev.EventName);
            sb.AppendLine(" -= handler);");
        }
        else
        {
            sb.AppendLine("                        global::System.EventHandler handler = (s, e) => callback(e);");
            sb.Append("                        typed.");
            sb.Append(ev.EventName);
            sb.AppendLine(" += handler;");
            sb.Append("                        return new global::Marionette.NET.Runtime.Internal.HandlerDisposable(() => typed.");
            sb.Append(ev.EventName);
            sb.AppendLine(" -= handler);");
        }

        // Phase 8.1: emit a typed SerializeArgs lambda when the args type's
        // transitive graph is fully source-gen-eligible (the validator's
        // JsonTypeCollector returned a non-null context property name).
        // Otherwise the descriptor's SerializeArgs stays default-null and the
        // runtime falls back to the legacy reflection-based path.
        if (ev.JsonRootContextName is { } jsonRoot)
        {
            sb.AppendLine("                    },");
            sb.AppendLine("                    SerializeArgs: static (value) =>");
            sb.AppendLine("                    {");
            sb.AppendLine("                        if (value is null) return null;");
            sb.Append("                        var __json = global::System.Text.Json.JsonSerializer.Serialize<");
            sb.Append(ev.ArgsTypeFullName);
            sb.Append(">((");
            sb.Append(ev.ArgsTypeFullName);
            sb.Append(")value, global::Marionette.Generated.MarionetteEventArgsJsonContext.Default.");
            sb.Append(jsonRoot);
            sb.AppendLine(");");
            sb.AppendLine("                        return global::System.Text.Json.Nodes.JsonNode.Parse(__json);");
            sb.AppendLine("                    }),");
        }
        else
        {
            sb.AppendLine("                    }),");
        }
    }

    // -------------------------------------------------------------------------
    // Phase 1.2: descriptor record types live in Marionette.NET.Runtime under
    // the `Marionette.Runtime.Manifest` namespace. The generator no longer
    // emits them inline; it `using`-imports them at the top of Marionette.g.cs
    // and references them by short name. See the EmitManifest header comment
    // and Phase 1.2's manifest-ownership decision in .phase1/1c-runtime.md.
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static string EscapeString(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        foreach (var c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    private static string StripGlobalPrefix(string s) =>
        s.StartsWith("global::", System.StringComparison.Ordinal) ? s.Substring("global::".Length) : s;

    /// <summary>
    /// Reserved-keyword guard. If a parameter happens to be named like a C#
    /// keyword (e.g. <c>class</c>, <c>new</c>) we prefix with <c>@</c>.
    /// </summary>
    private static string SafeIdentifier(string name)
    {
        if (s_csharpKeywords.Contains(name)) return "@" + name;
        return name;
    }

    private static string TempIdentifierSuffix(string ident) =>
        ident.StartsWith("@", System.StringComparison.Ordinal) ? ident.Substring(1) : ident;

    private static readonly HashSet<string> s_csharpKeywords = new(System.StringComparer.Ordinal)
    {
        "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
        "continue","decimal","default","delegate","do","double","else","enum","event","explicit",
        "extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int",
        "interface","internal","is","lock","long","namespace","new","null","object","operator","out",
        "override","params","private","protected","public","readonly","ref","return","sbyte","sealed",
        "short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
        "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while"
    };
}
